### PR TITLE
Big changes

### PR DESCRIPTION
**Pull request by cyber-atomus**
Added new functionality, updated readme.md (this needs some work).

It now uses _wxtoimg_ capabilities to create maps and images.

Preliminary work to function with '_doppler_' tool.

Added fresh Kepplers, updated keppler refresher links to recent celestrak files.

It still needs more programming.

### CODE REVIEW

**Comment by DrPaulBrewer** [comment]
Chris:

Thank you for your pull request.  I am not certain I can accept it as is, but it is nice to see someone take interest in this rough early code.

We may have different opinions as to how to proceed.  I release under GNU GPL v2 LICENSE so as long as you follow that you are OK.

You may note I have my own APT decoder.  There is a reason for that.  For one thing, the doppler-induced curvature makes for an interesting science demonstration and can be used to estimate the speed of the satellite.  Also you get to see the rough picture of land as the satellite actually sees it. Instead of a beautiful pretend map with the clouds overlayed as with other decoders.  And land features are always in the correct location when the land image is the original.  I have seen maps produced by others where major features are misplaced, e.g. the Great Lakes appearing in the wrong state.   So I do not want to replace that with wxtoimg but it should be an option.

If you want to work together, perhaps we let the end user decide with various
--option-settings or a config file (yaml is easiest, though json is ok too) what they want for the acquisition step (e.g command to record radio signal), the conversion step (command to change recording into image, spectrum, or anything else), and  any post-conversion steps (such as posting to internet, twitter, etc). This framework is way to drive more interest in programming not only by us but by others.

I have a dedicated computer that runs this code, but not much time to write more code at the moment.  

One improvement I could share is a SDR recorder written in gnu-radio.  I also have a very simple way to dump the images to a directory that a webserver can serve.  

At one time I had it running on small hobbyist ARM computer, not raspberry pi but something called cubieboard.  Original raspberry pi was too slow. With a pentium, GNU Radio can be run and seems to be better software but with more overhead than rtl_fm

I can make a tarball snapshot of the running system and you can reuse anything you find interesting.

Looking forward to your reply,

Paul Brewer
KI6CQ

**Comment by cyber-atomus** [comment]
Paul,
thank you for your fast reply. I wasn't expecting it so fast. I'd like to
clarify few things if it's OK for you.
I'm a hobbyist who looked for an automated APT reception, I have spare
dongle and wanted to use it best as I can. It's a very low-gain and noisy
one (fc0013), I'll be buying a r820t or e4000 as soon as I can.

I understand your reasoning, my goal was to choose between different
decoders. And to create good config base - json or plain configfile.
Anyway, we can keep two different branches/forks or completely different
pieces of software. It's up to you, all props are to you for the basic
work. About the misplaced overlays, I've added the option for user to
choose if he wants the overlay - misplaced overlay map is common problem
which I think can't be automated (wx autoprocess). My approach was to
generate map exactly at the date specified by recording and then add it to
image generated from WAV - with "-A" option which bypasses detection of APT
signal - word to word.
There's another idea - to have an option to record only if the satellite
would have highest point (azimuth) higher than value set in settings -
there's a lot of '0' passes - satellite gently over horizon which doesn't
produce any readable output - but this could be my antenna setup too. I'll
be installing new QFH soon.

The spectrum is generated by sox to judge what was the reason of noise in
image - interference or lack of signal. I can't wait what I'll see in the
morning after few sat passes. It can show the doppler shift too!

I can't do Python a lot, I worked in IT/Telco before and I growed on PHP,
shell scripts and SQL things :-) But I learn fast...

And yes, it has a great potential - using more complicated config one could
even receive APRS satcoms and read it later. I use this tool (and develop
it) on my remote oldie-but-goodie HP t5720, which is located at my
gardenhouse (we have a very cheap gardens here in Poland), hidden in the
attic and VPNed to my home. There are even public graphs of various sensors
on my "webpage". I strip only alarm/webcams related graphs/alarms for
security reasons. I'm currently long-term unemployed and can't afford embed
system right now to test the software on ARM, I had a beaglebone but I
fried it playing with servos. For SDRs I assume CPU has to have a lot of
computing power (math), and judging from the timing of image/map generation
- an old GeodeNX is far better than any Pi Cortex core. Do you think proper
  volk profiling would help (eg by running volk_profile)?

Once again, thank you for the contact - it was nice hearing you.
Krzysztof "Chris" Lewandowski

**Comment by DrPaulBrewer** [comment]
Chris:

Here is a copy of /etc, /usr/local, and /home/rx off of the computer dedicated to running this software.
It is about 1 GB and is temporarily hosted with google in euro zone.

I believe you can get this with "wget" or "curl" from command line, like this:

`wget https://storage.googleapis.com/ki6cq-euro/ki6cq-dedicated-rx-partial-dump-2016Mar.tgz`

and then to unpack, of course:

`tar xvfz ki6cq-dedicated-rx-partial-dump-2016Mar.tgz` which will require maybe 5-10 GB I think.

/home/rx is where the latest copy of the automation software lives, but I supply the other directories for understanding any configuration of system services.  Secret files like /etc/passwd or ssh keys have been removed from this dump.

Please let me know that you have downloaded this as I would like to take it offline.  There are costs, very small, about US$1/per 5 downloads.  But I do not want to pay for 1000s of download.

One of the interesting problems is which images to keep and which to throw away.  It would be nice to automate this decision, one way seems to be laplace filter summation.  I have a small script for this called niceapt.  There might be others.  Perhaps a neural net?  

I also have 40GB (compressed) of recordings/imagery.  I can get these to you somehow if it would be helpful.  

Paul
KI6CQ

**Comment by cyber-atomus** [comment]
Paul,

Thank you for the file. I have downloaded it and you can remove it from
storage. I will look into it this weekend.

I think neural net is like shooting the fly with the cannon and laplace
sounds good.  On the side I was thinking of very simple finding of the
subcarrier with sox filters, measure its strength and decide if it's strong
enough to get readable output. That's basically how I check if my burglar
alarm turned on at the remote location.

Imagery wouldn't be needed as I have a bunch of manual recordings which I
can compare to. For 40GiB it would be faster to place a BD disk in the
plane than uploading/downloading it somewhere :)

Still, I'm waiting to raise some money to get a new SDR to replace poor
fc0013 tuner to get any readable picture. Perhaps next week.

Thank you,
Chris

**Comment by DrPaulBrewer** [comment]
I have a used e4000 or r820 tuner that I would sell for payment in bitcoin
or ethereum.

On Sat, Mar 12, 2016 at 5:25 AM, Chris Lewandowski <notifications@github.com

**Comment by DrPaulBrewer** [comment]
I have done the sox spectrograms.  They are in that 40gb of data.

Simply detecting signal strength of the subcarrier tone is misleading.

Here is what happens in weak pass:

The output contains the subcarrier tone and white noise.

The FM carrier signal is not strong enough to cause the FM quieting effect.

That tone is the first thing the receiver hears

Here is what happens in good pass:

The tone is heard first.

Then later the receiver output becomes quiet except for tone, harmonics,
and clicking sounds.

This shows up in spectrogram as dark red and purple across most of audio
spectrum,

As satellite becomes weak the opposite occurs, it becomes noisy, and then
finally loses tone.

**Comment by cyber-atomus** [comment]
Paul,
Thank you for the tuners offer, but it won't be needed. I do not use
cryptocurrencies and getting tuners on Allegro/ebay is easy enough. I just
need to raise some money, as I said before I'm currently long-term
unemployed (actually situation is a bit harder than that, but that's not
the point of the discussion) and do stuff - to learn more and simply to not
forget how to do "IT stuff".

About sox spectrograms, it's easier to do them on the site, really -
getting 40gigs of data is a little too much for me. I already made some
images of good and weak passes.

I need to reconsider it all once again,
thank you again,
Chris.

**Comment by DrPaulBrewer** [comment]
Good luck with your fork. I may post a link to it.

**Pull request closed without merging**
